export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  // LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  // LOGOUT_FAILURE: "LOGOUT_FAILURE",

  UPDATE_INFORMATION_SUCCESS: "UPDATE_INFORMATION_SUCCESS",

  CHANGE_INFORMATION_REQUEST: "CHANGE_INFORMATION_REQUEST",
  CHANGE_INFORMATION_SUCCESS: "CHANGE_INFORMATION_SUCCESS",
  CHANGE_INFORMATION_FAILURE: "CHANGE_INFORMATION_FAILURE",

  GET_INFORMATION_REQUEST: "GET_INFORMATION_REQUEST",
  GET_INFORMATION_SUCCESS: "GET_INFORMATION_SUCCESS",
  GET_INFORMATION_FAILURE: "GET_INFORMATION_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
};


export const postConstants = {
  GET_ALL_POST_COMPLETED_REQUEST: "GET_ALL_POST_COMPLETED_REQUEST",
  GET_ALL_POST_COMPLETED_SUCCESS: "GET_ALL_POST_COMPLETED_SUCCESS",
  GET_ALL_POST_COMPLETED_FAILURE: "GET_ALL_POST_COMPLETED_FAILURE",

  GET_ALL_POST_MUST_VERIFY_REQUEST: "GET_ALL_POST_MUST_VERIFY_REQUEST",
  GET_ALL_POST_MUST_VERIFY_SUCCESS: "GET_ALL_POST_MUST_VERIFY_SUCCESS",
  GET_ALL_POST_MUST_VERIFY_FAILURE: "GET_ALL_POST_MUST_VERIFY_FAILURE",

  ACCEPT_POST_REQUEST: "ACCEPT_POST_REQUEST",
  ACCEPT_POST_SUCCESS: "ACCEPT_POST_SUCCESS",
  ACCEPT_POST_FAILURE: "ACCEPT_POST_FAILURE",

  DENY_POST_REQUEST: "DENY_POST_REQUEST",
  DENY_POST_SUCCESS: "DENY_POST_SUCCESS",
  DENY_POST_FAILURE: "DENY_POST_FAILURE",

  DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
};

export const tutorConstants = {
  GET_ALL_TUTOR_MUST_VERIFY_REQUEST: "GET_ALL_TUTOR_MUST_VERIFY_REQUEST",
  GET_ALL_TUTOR_MUST_VERIFY_SUCCESS: "GET_ALL_TUTOR_MUST_VERIFY_SUCCESS",
  GET_ALL_TUTOR_MUST_VERIFY_FAILURE: "GET_ALL_TUTOR_MUST_VERIFY_FAILURE",

  GET_ALL_TUTOR_COMPLETED_REQUEST: "GET_ALL_TUTOR_COMPLETED_REQUEST",
  GET_ALL_TUTOR_COMPLETED_SUCCESS: "GET_ALL_TUTOR_COMPLETED_SUCCESS",
  GET_ALL_TUTOR_COMPLETED_FAILURE: "GET_ALL_TUTOR_COMPLETED_FAILURE",

  ACCEPT_TUTOR_REQUEST: "ACCEPT_TUTOR_REQUEST",
  ACCEPT_TUTOR_SUCCESS: "ACCEPT_TUTOR_SUCCESS",
  ACCEPT_TUTOR_FAILURE: "ACCEPT_TUTOR_FAILURE",
  
  DENY_TUTOR_REQUEST: "DENY_TUTOR_REQUEST",
  DENY_TUTOR_SUCCESS: "DENY_TUTOR_SUCCESS",
  DENY_TUTOR_FAILURE: "DENY_TUTOR_FAILURE",
};

export const customerConstants = {
  GET_ALL_CUSTOMER_REQUEST: "GET_ALL_CUSTOMER_REQUEST",
  GET_ALL_CUSTOMER_SUCCESS: "GET_ALL_CUSTOMER_SUCCESS",
  GET_ALL_CUSTOMER_FAILURE: "GET_ALL_CUSTOMER_FAILURE",

  ADD_CUSTOMER_REQUEST: "ADD_CUSTOMER_REQUEST",
  ADD_CUSTOMER_SUCCESS: "ADD_CUSTOMER_SUCCESS",
  ADD_CUSTOMER_FAILURE: "ADD_CUSTOMER_FAILURE",

  UPDATE_CUSTOMER_REQUEST: "UPDATE_CUSTOMER_REQUEST",
  UPDATE_CUSTOMER_SUCCESS: "UPDATE_CUSTOMER_SUCCESS",
  UPDATE_CUSTOMER_FAILURE: "UPDATE_CUSTOMER_FAILURE",

  DELETE_CUSTOMER_REQUEST: "DELETE_CUSTOMER_REQUEST",
  DELETE_CUSTOMER_SUCCESS: "DELETE_CUSTOMER_SUCCESS",
  DELETE_CUSTOMER_FAILURE: "DELETE_CUSTOMER_FAILURE",
};

export const classConstants = {
  GET_ALL_CLASS_REQUEST_OPEN_REQUEST: "GET_ALL_CLASS_REQUEST_OPEN_REQUEST",
  GET_ALL_CLASS_REQUEST_OPEN_SUCCESS: "GET_ALL_CLASS_REQUEST_OPEN_SUCCESS",
  GET_ALL_CLASS_REQUEST_OPEN_FAILURE: "GET_ALL_CLASS_REQUEST_OPEN_FAILURE",

  ACCEPT_CLASS_OPEN_REQUEST: "ACCEPT_CLASS_OPEN_REQUEST",
  ACCEPT_CLASS_OPEN_SUCCESS: "ACCEPT_CLASS_OPEN_SUCCESS",
  ACCEPT_CLASS_OPEN_FAILURE: "ACCEPT_CLASS_OPEN_FAILURE",


};
